# Generated by Django 3.2.7 on 2022-12-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excalorieApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfooditem',
            old_name='customer',
            new_name='profile',
        ),
    ]
