# Generated by Django 3.2.7 on 2022-12-07 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('excalorieApp', '0003_auto_20221207_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='profile',
        ),
        migrations.AddField(
            model_name='userfooditem',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
