# Generated by Django 3.2.7 on 2022-12-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excalorieApp', '0004_auto_20221207_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfooditem',
            name='profile',
            field=models.ManyToManyField(blank=True, to='excalorieApp.Profile'),
        ),
    ]
