# Generated by Django 3.2.7 on 2022-12-08 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excalorieApp', '0005_userfooditem_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfooditem',
            name='user',
        ),
    ]
