# Generated by Django 3.2.7 on 2022-12-08 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excalorieApp', '0008_auto_20221208_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfooditem',
            name='profile',
            field=models.ManyToManyField(blank=True, default='user', editable=False, to='excalorieApp.Profile'),
        ),
    ]
