# Generated by Django 3.2.7 on 2022-12-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excalorieApp', '0009_alter_userfooditem_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfooditem',
            name='profile',
            field=models.ManyToManyField(blank=True, default='user', to='excalorieApp.Profile'),
        ),
    ]
