# Generated by Django 3.2.7 on 2022-12-08 12:07

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excalorieApp', '0010_alter_userfooditem_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userfooditem',
            name='profile',
            field=models.ManyToManyField(blank=True, default='profile', to='excalorieApp.Profile'),
        ),
    ]
